name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull Docker image
      run: docker pull ghcr.io/growup5/ride/python-app:545240ad87de2f0d11e314afc5d2fd18cf55d856

    - name: Deploy with Docker Compose
      run: docker-compose up -d
