name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image:latest .

      - name: Run Docker container
        run: docker run -d -p 8080:80 my-docker-image:latest

      - name: Test service
        run: |
          curl http://localhost:8080
