name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          IMAGE_NAME="python-app:${{ github.sha }}"
          docker buildx build --tag $IMAGE_NAME .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name python-app-container $IMAGE_NAME

      - name: Verify Docker container is running
        run: |
          docker ps -a
