name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
                                                      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ride/python-app:${{ github.sha }}"
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          docker buildx build --tag $IMAGE_NAME_LOWER --push .

      - name: Run Docker container
        run: |
           docker run -d -p 8080:8080 ghcr.io/growup5/ride/python-app:a0b6072f6872c2679c12e3db029eedfed0a7905f

