name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          cd app && docker build -t my/testapp .
      
      - name: Start Testapp Container
        run: docker run -d -p 8080:8080 my/testapp
      
      - name: Check Docker Container
        id: check  
        run: docker ps
      
      - name: Test App in Container
        id: test
        run: curl -v http://localhost:8080/data