name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t python-app:latest .

      - name: Run Docker container with port mapping
        run: docker run -d -p 8080:8080 python-app:latest
